export const PlatformCategories = ['General', 'Deployment', 'Identifiers', 'Telecom', 'Hardware'];
import config from '../../../config';

export const PlatformFilters = [
	{
	  key: 'ref',
	  label: 'Reference (Start)',
	  type: 'text',
	  category: 'General',
	  defaultDisplayed: true,
	},
	{
		key: 'exactRef',
		label: 'Exact Reference',
		type: 'text',
		category: 'General',
		defaultDisplayed: false,
	  },
	  {
		  key: 'name',
		  label: 'Name',
		  type: 'text',
		  category: 'General',
		  defaultDisplayed: false,
		},
	{
	  key: 'deplDateFrom',
	  label: 'Deployed After',
	  type: 'date',
	  category: 'Deployment',
	  defaultDisplayed: true,
	},
	{
	  key: 'deplDateTo',
	  label: 'Deployed Before',
	  type: 'date',
	  category: 'Deployment',
	  defaultDisplayed: false,
	},
	{
	  key: 'networks',
	  label: 'Network',
	  type: 'networkSelect',
	  category: 'General',
	  url: `${config.oldDashboardApiRoot}/NetworkList?scope=theme&themeId=1000641`,
	  defaultDisplayed: true,
	},
	{
	  key: 'country',
	  label: 'Country',
	  type: 'countrySelect',
	  category: 'General',
	  url: `${config.apiRoot}/data/country?exp=["active = 1"]`, 
	  defaultDisplayed: true,
	},
	{
	  key: 'programs',
	  label: 'Program',
	  type: 'multiSelect',
	  category: 'General',
	  url: `${config.apiRoot}/data/program`, 
	  defaultDisplayed: false,
	},
	{
	  key: 'variables',
	  label: 'Variable',
	  type: 'multiSelect',
	  category: 'General',
	  url: `${config.apiRoot}/data/variable`,
	  defaultDisplayed: true,
	},
	{
	  key: 'status',
	  label: 'Status',
	  type: 'multiSelect',
	  category: 'General',
	  url: `${config.apiRoot}/data/platformstatus`, 
	  defaultDisplayed: true,
	  sortBy:'rank'
	},
	{
		key: 'serialId',
		label: 'Serial number',
		type: 'text',
		category: 'Identifiers',
		defaultDisplayed: false,
	},
	{
		key: 'wmoId',
		label: 'GTS-ID',
		type: 'text',
		category: 'Identifiers',
		defaultDisplayed: false,
	},
	{
		key: 'internalId',
		label: 'Internal ID',
		type: 'text',
		category: 'Identifiers',
		defaultDisplayed: false,
	},
	{
		key: 'wigosId',
		label: 'WIGOS ID',
		type: 'text',
		category: 'Identifiers',
		defaultDisplayed: false,
	},
	{
	  key: 'telType',
	  label: 'Telecom type',
	  type: 'multiSelect',
	  category: 'Telecom',
	  url: `${config.apiRoot}/data/telecomtype`, 
	  defaultDisplayed: false
	},
	{
	  key: 'telServices',
	  label: 'Telecom service',
	  type: 'multiSelect',
	  category: 'Telecom',
	  url: `${config.apiRoot}/data/telecomservice`, 
	  defaultDisplayed: false
	},
	{
		key: 'telNum',
		label: 'Telecom number',
		type: 'text',
		category: 'Telecom',
		defaultDisplayed: false,
	},
	{
		key: 'imei',
		label: 'IMEI',
		type: 'text',
		category: 'Telecom',
		defaultDisplayed: false,
	},
	{
	  key: 'battery',
	  label: 'Battery',
	  type: 'singleSelect',
	  category: 'Hardware',
	  url: `${config.apiRoot}/data/platformbattery`, 
	  defaultDisplayed: false
	},
  ];
